from django.forms import BooleanField, CharField, Form, Textarea, TextInput


class AddEditForm(Form):
    yearDeveloped = CharField(max_length=4, required=False)
    name = CharField(max_length=200, widget=TextInput(attrs={'size': '100'}))
    author = CharField(max_length=200, required=False, widget=TextInput(attrs={'size': '100'}))
    url = CharField(max_length=200, widget=TextInput(attrs={'size': '100'}))
    description = CharField(widget=Textarea(attrs={'cols': '100'}))
    communitySizeUrban = BooleanField()
    communitySizeRural = BooleanField()
    assessmentFocusDevelopment = BooleanField()
    assessmentFocusPhysical = BooleanField()
    assessmentFocusPolicy = BooleanField()
    assessmentFocusWalkability = BooleanField()
    audienceElected = BooleanField()
    audienceLaypersons = BooleanField()
    audiencePlanners = BooleanField()
    audienceProfessionals = BooleanField()
    audienceSchool = BooleanField()
    topicTransportation = BooleanField()
    topicHousing = BooleanField()
    topicInvestment = BooleanField()
    topicCompact = BooleanField()
    topicHealth = BooleanField()
    topicPreservation = BooleanField()
