from django.forms import BooleanField, CharField, Form, Textarea, TextInput


class AddEditForm(Form):
    yearDeveloped = CharField(max_length=4, required=False)
    name = CharField(max_length=200, widget=TextInput(attrs={'size': '100'}))
    author = CharField(max_length=200, required=False, widget=TextInput(attrs={'size': '100'}))
    url = CharField(max_length=200, widget=TextInput(attrs={'size': '100'}))
    description = CharField(widget=Textarea(attrs={'cols': '100'}))
    communitySizeUrban = BooleanField(required=False)
    communitySizeRural = BooleanField(required=False)
    assessmentFocusDevelopment = BooleanField(required=False)
    assessmentFocusPhysical = BooleanField(required=False)
    assessmentFocusPolicy = BooleanField(required=False)
    assessmentFocusWalkability = BooleanField(required=False)
    audienceElected = BooleanField(required=False)
    audienceLaypersons = BooleanField(required=False)
    audiencePlanners = BooleanField(required=False)
    audienceProfessionals = BooleanField(required=False)
    audienceSchool = BooleanField(required=False)
    topicTransportation = BooleanField(required=False)
    topicHousing = BooleanField(required=False)
    topicInvestment = BooleanField(required=False)
    topicCompact = BooleanField(required=False)
    topicHealth = BooleanField(required=False)
    topicPreservation = BooleanField(required=False)
