#!/bin/bash

OWNER="safestates"
NAME="$OWNER"
PROJECT_NAME="SafeStates"
WSGI_NAME="SafeStates"
PORT=31200
WORKERS=4
ACCESSLOG="/home/$OWNER/django_logs/access.log"
ERRORLOG="/home/$OWNER/django_logs/error.log"

VIRTUALENV="$OWNER"
CONFDIR="/home/$OWNER/$PROJECT_NAME"
VIRTUALENVDIR="/home/$OWNER/.virtualenvs"
GUNICORN_RUN="$VIRTUALENVDIR/$VIRTUALENV/bin/gunicorn"
GUNICORN_LOGS="--access-logfile=$ACCESSLOG --error-logfile=$ERRORLOG"
BINDIP="127.0.0.1"
PID="/home/$OWNER/$PROJECT_NAME.pid"
VENV_ACTIVATION="sh $VIRTUALENVDIR/$VIRTUALENV/bin/activate"
RETVAL=0

export PYTHONPATH=$PYTHONPATH:$CONFDIR;
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib/
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
cd $CONFDIR;
$VENV_ACTIVATION; $GUNICORN_RUN -b $BINDIP:$PORT -n $NAME -w $WORKERS -p $PID $GUNICORN_LOGS -D ${WSGI_NAME}.wsgi:application && exit 0